[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.loadgenerator"
    Version = "1.2.2"
    ChartName = "chart/loadgenerator"
    DockerRepo = "quay.io/hipsterstore/loadgenerator"
    GitUrl = "https://github.com/ortelius/store-loadgenerator"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]